In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
# Checking NumPy version
import numpy as np
print(np.__version__)


2.0.2


In [ ]:
# Create a NumPy ndarray Object
# NumPy is used to work with arrays. The array object in NumPy is called ndarray.

# We can create a NumPy ndarray object by using the array() function.


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

# Example: Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [ ]:
# Dimensions in Arrays
# 👉  A dimension in arrays is one level of array depth (nested arrays).
# 👉  Dimensions tell you how data is arranged inside an array — whether it’s a single line, a table, or a box of numbers.
# 👉 In NumPy, dimensions are also called axes.

# Nested array: are arrays that have arrays as their elements.

# TYPES OF DIMENSIONS IN ARRAYS
# 👉 0-D Arrays: 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
# - It has no directions (no rows, no columns).
# - It contains just one single value.
# - Think of it as a number stored inside a NumPy array container.

# Example:Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

42


In [ ]:
# 👉 1-D Arrays: An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
# - These are the most common and basic arrays.
# - Looks like a list

# Example:Create a 1-D array containing the values 1,2,3,4,5

# Dimension: 1

# Shape: (5,)

# Example: list of numbers

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
# 👉 2-D Arrays: Looks like a table (rows & columns)
# Example:Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

# Dimension: 2

# Shape: (2, 3) → 2 rows, 3 columns

# Example: spreadsheet / matrix

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 👉 3-D arrays: Looks like multiple tables stacked together
# Example:Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:


 # Dimension: 3

# Shape: (2,2, 3) → 2 → number of “blocks” (outermost lists), 2 → number of rows in each block ,3 → number of columns in each row

# Example: stack of spreadsheets

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# How to check dimensions
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr.shape   # size of each dimension

(2, 2, 3)

In [ ]:
# How to check dimensions
arr.ndim    # number of dimensions

3

In [ ]:
# Each level of brackets [ adds one dimension, as long as the nested lists are uniform in size.
# Outermost [ → dimension 1

# Next [[] inside → dimension 2

# Next [[[ inside that → dimension 3

# So yes, because you have [[[ ... ]]] → it is 3D.

In [ ]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
# Example:Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Higher Dimensional Arrays
# An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.

In [ ]:
# Example: Create an array with 5 dimensions and verify that it has 5 dimensions
import numpy as np
arr = np.array([1,2,3,4,5,6,7], ndmin = 5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5 6 7]]]]]
number of dimensions : 5


In [ ]:
# NumPy Array Indexing

# Access Array Elements
# Array indexing is the same as accessing an array element. You can access an array element by referring to its index number.

# The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
# Example:Get the first element from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
# Example: Get third and fourth elements from the following array and add them.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
# Access 2-D Arrays:To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

# Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [ ]:
# Example:Access the element on the first row, second column:

# Think of it like a small table (spreadsheet):

# Row 0 → 1  2  3  4  5
# Row 1 → 6  7  8  9 10

arr[0, 1]


# Means:

# 0 → first row (Python starts counting from 0)

# 1 → second column

# So NumPy goes to: ➡ Row 0, Column 1



import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
# Practice Questions (NumPy Array Indexing)

# Question 1 : 👉 Print the third element of the first row
# Think of it like a small table (spreadsheet):

# Row 0 → 10  20  30
# Row 1 → 40  50  60

# arr[0, 2]



arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("The third element of the first row is:", arr[0,2])


The third element of the first row is: 30


In [ ]:
# Question 2 : 👉 Print the first element of the second row

arr = np.array([[5, 15, 25],
                [35, 45, 55]])
# Row 0 → 5  15  25
# Row 1 → 35  45  55

# arr[1, 0]
print("The first element of the second row is:", arr[1,0])




The first element of the second row is: 35


In [ ]:
# Question 3: 👉 Print the middle element

arr = np.array([[1, 4, 7],
                [2, 5, 8],
                [3, 6, 9]])

# Row 0 → 1 4  7
# Row 1 → 2  5  8
# Row 2 → 3  6  9

print("The middle element is:", arr[1,1])






The middle element is: 5


In [ ]:
# Question 4: 👉 Print the last element of the second row

arr = np.array([[100, 200, 300, 400],
                [500, 600, 700, 800]])

print("The last element of the second row is: ", arr[1,3])




The last element of the second row is:  800


In [ ]:
# Question 5: 👉 Print the element at first row, first column

arr = np.array([[9, 8],
                [7, 6]])

print("The  element at first row, first column is:", arr[0,0])



The  element at first row, first column is: 9


In [ ]:
# Access 3-D Arrays
# To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
# Example:Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# What does the question mean?

# 👉 “third element of the second array of the first array”

# First array → index 0

# Second array inside it → index 1

# Third element inside that → index 2

# Row 0 → 1 2  3
# Row 1 → 4  5  6
# Row 2 → 7  8  9
# Row 3 → 10 11  12

# arr[0,1,2]



print(arr[0, 1, 2])

6


In [ ]:
# Negative Indexing
# Use negative indexing to access an array from the end.

# Example:Print the last element from the 2nd dim:

import numpy as np
# Row 0 → 1 2  3 4 5
# Row 1 → 6 7 8 9 10
# [1,-1]

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
# Practice for you

# 1️⃣ Print the last element of this array:

arr = np.array([5, 10, 15, 20])

print("The last element of this array is:", arr[-1])




The last element of this array is: 20


In [ ]:
# 2️⃣ Print the last column of the first row:

arr = np.array([[3, 6, 9],
                [12, 15, 18]])

print("The last column of the first row:", arr [0,-1])




The last column of the first row: 9


In [ ]:
# 3️⃣ Print the last element of the last row of the last block:

# block 0  → [1,2,3], [4,5,6]]
# block 1 → [7,8,9], [10,11,12]

# Blocks → 2 (index 0 and 1)

# Rows per block → 2 (index 0 and 1)

# Elements per row → 3 (index 0, 1, 2 or -1)
# 1 → last block

#-1 → last row

#-1 → last element

arr = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])

print("The last element of the last row of the last block is:", arr[1, -1, -1])

The last element of the last row of the last block is: 12


In [ ]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# block 0  → [1, 2], [3, 4]
# block 1 → [5, 6], [7, 8]]

# 1 → last block:  [5, 6], [7, 8]]


# 1 → last row: [7, 8]

# 0 → first element: 7


print(arr[1, 1, 0])

7


In [ ]:
# NumPy Array Slicing

# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].

# We can also define the step, like this: [start:end:step].

# If we don't pass start its considered 0

# If we don't pass end its considered length of array in that dimension

# If we don't pass step its considered 1

In [ ]:
# Example:Slice elements from index 1 to index 5 from the following array:
# Note: The result includes the start index, but excludes the end index.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
# Example:Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [ ]:
# Example:Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [ ]:
# Negative Slicing:Use the minus operator to refer to an index from the end:

# Example:Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
# STEP:Use the step value to determine the step of the slicing:

# Example:Return every other element from index 1 to index 5:

# [start:end:step]

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
# Example:Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
# Slicing 2-D Arrays
# Example: From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# Element 0:[1, 2, 3, 4, 5]
# Element 1:[6, 7, 8, 9, 10]
# [1,1:4]


print(arr[1, 1:4])

[7 8 9]


In [ ]:
# Example:From both elements, return index 2:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
# Example:From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:2])

[1 2]


In [ ]:
# NumPy Data Types
# By default Python have these data types:

# 1. strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# 2. integer - used to represent integer numbers. e.g. -1, -2, -3
# 3. float - used to represent real numbers. e.g. 1.2, 42.42
# 4. boolean - used to represent True or False.
# 5. complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy
# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

# Below is a list of all data types in NumPy and the characters used to represent them.

# 1. i - integer
# 2. b - boolean
# 3. u - unsigned integer
# 4. f - float
# 5. c - complex float
# 6. m - timedelta
# 7. M - datetime
# 8. O - object
# 9. S - string
# 10.U - unicode string
# 11.V - fixed chunk of memory for other type ( void )


In [ ]:
# Checking the Data Type of an Array
# The NumPy array object has a property called dtype that returns the data type of the array:

# Example : Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int64


In [ ]:
# Example:Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
# Creating Arrays With a Defined Data Type
# We use the array() function to create arrays.
# This function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [ ]:
# Example:Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# Example:Create an array with data type unicode string :

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='U')

print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


In [ ]:
# For i, u, f, S and U we can define size as well.

# Example:Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype ='i4')

print(arr)
print(arr.dtype)


[1 2 3 4]
int32


In [ ]:
# Example:A non integer string like 'a' can not be converted to integer (will raise an error):

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
# Converting Data Type on Existing Arrays

# The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

# The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
# Example: Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# Example:Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
# Example:Change data type from integer to boolean:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
# Exercise:Consider the following code, What will be the printed result?
import numpy as np
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)


[ True False  True]


In [ ]:
# NumPy Array Copy vs View

# The Difference Between Copy and View

# 1. The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

# 2. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

# 3. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

# COPY:
# Example: Make a copy, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

# The copy SHOULD NOT be affected by the changes made to the original array.



[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# VIEW:
# Example: Make a view, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

# The view SHOULD be affected by the changes made to the original array.



[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# One-line rule to remember (exam-friendly)

# view() shares memory, copy() does not, copy() makes a new book

In [ ]:
# Check if Array Owns its Data
# As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

# Every NumPy array has the attribute base that returns None if the array owns the data.(copy())

# Otherwise, the base  attribute refers to the original object.(view())

# NumPy uses the base attribute to tell you whether an array owns its data or is just borrowing it.

# base is None → the array OWNS its data (copy)

# base is NOT None → the array is a VIEW (borrowing data)

In [ ]:
# Example: Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
# Exercise: Consider the following code:
import numpy as np
original_array = np.array([1, 2, 3])
x = original_array.copy()
x[0] = 5
print(original_array)
print(x)

[1 2 3]
[5 2 3]


In [ ]:
# Shape of an Array
# The shape of an array is the number of elements in each dimension.

# Get the Shape of an Array
# NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
# 1-D  Shape = number of elements

# 2-D  Shape = rows × columns (number of rows, number of columns)

# 3-D  Shape = blocks × rows × columns (number of blocks, rows per block, columns per row)

# 4-D  Shape = groups × blocks × rows × columns  (number of groups, blocks per group, rows per block, columns per row)



In [ ]:
# Example: Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
# 2-D Array Example (Rows × Columns)

import numpy as np

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr_2d.shape)

(2, 3)


In [ ]:
# 3-D Array Example (Blocks × Rows × Columns)

arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr_3d.shape)

(2, 2, 3)


In [ ]:
# For example on 3 D Array:

# ❓ How many tables (blocks)? → 2

# ❓ In EACH table, how many rows? → 2

# ❓ In EACH row, how many numbers? → 3

# 👉 So: shape = (2 blocks, 2 rows, 3 columns)

In [ ]:
# 4-D Array Example (Groups × Blocks × Rows × Columns)
# Meaning:

# 2 groups

# 2 blocks per group

# 2 rows per block

# 3 columns per row

arr_4d = np.zeros((2, 2, 2, 3))
print(arr_4d.shape)

(2, 2, 2, 3)


In [ ]:
import numpy as np

arr = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
])
print(arr.shape)


(2, 3, 2)


In [ ]:
# Questions:

# 1. What is the shape of this array?: (2, 3, 2)

# 2. How many blocks does it have?: 2

# 3. How many rows per block?: 3

# 4. How many columns per row?: 2

In [ ]:
import numpy as np

arr = np.zeros((2, 2, 3, 4))
print(arr.shape)


(2, 2, 3, 4)


In [ ]:
# Questions:

# 1. What is the shape of this array?: (2, 2, 3, 4)

# 2. How many groups does it have?: 2

# 3. How many blocks per group?: 2

# 4. How many rows per block?: 3

# 5. How many columns per row? 4

# Group 1
# ├─ Block 1
# │   [0 0 0 0]  <- row 1
# │   [0 0 0 0]  <- row 2
# │   [0 0 0 0]  <- row 3
# └─ Block 2
#     [0 0 0 0]  <- row 1
#     [0 0 0 0]  <- row 2
#     [0 0 0 0]  <- row 3

# Group 2
# ├─ Block 1
# │   [0 0 0 0]  <- row 1
# │   [0 0 0 0]  <- row 2
# │   [0 0 0 0]  <- row 3
# └─ Block 2
#     [0 0 0 0]  <- row 1
#     [0 0 0 0]  <- row 2
#     [0 0 0 0]  <- row 3


In [ ]:
# Example:Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
# Dimension 1 → [                       ]

# Dimension 2 →   [                     ]


# Dimension 3 →     [                   ]

# Dimension 4 →       [                 ]

# Dimension 5 →         [1  2  3  4]   ← actual numbers (columns)


In [ ]:
# Exercise: Consider the following code:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [ ]:
# NumPy Array Reshaping
# Reshaping arrays: Reshaping means changing the shape of an array.

# The shape of an array is the number of elements in each dimension. By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [ ]:
# Reshape From 1-D to 2-D
# Example: Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements: 4 rows, 3 columns

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshape From 1-D to 3-D
# Example: Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements: 2 blocks, 3 rows, 2 columns

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Can We Reshape Into any Shape?
# Yes, as long as the elements required for reshaping are equal in both shapes.

# We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [ ]:
# Returns Copy or View?
# Example: Check if the returned array is a copy or a view:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
# Unknown Dimension
# You are allowed to have one "unknown" dimension.

# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

# Pass -1 as the value, and NumPy will calculate this number for you.

# Example: Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Shape = (2, 2, 2) ✅

# 3-D array

# 2 blocks

# 2 rows per block

# 2 columns per row

In [ ]:
# Flattening the arrays
# Flattening array means converting a multidimensional array into a 1D array.

# We can use reshape(-1) to do this.

# Example : Convert the array into a 1D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4]


In [ ]:
import numpy as np

arr = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
])

newarr = arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc.
# These fall under Intermediate to Advanced section of numpy.

In [ ]:
# Exercise : Consider the following code:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(6)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
# NumPy Array Iterating
# Iterating means going through elements one by one.

# As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python. If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
# Example : Iterate on the elements of the following 1-D array:

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


In [ ]:
# Iterating 2-D Arrays : In a 2-D array it will go through all the rows.

# Example : Iterate on the elements of the following 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
# If we iterate on a n-D array it will go through n-1th dimension one by one.

# To return the actual values, the scalars, we have to iterate the arrays in each dimension.

# Example: Iterate on each scalar element of the 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


In [ ]:
# First iteration → x = [1, 2, 3]

# Second iteration → x = [4, 5, 6]


# for y in x:


# x is a 1-D array (a row)

# Each y is a single number (scalar) inside that row

# So:

# From [1, 2, 3] → y = 1, then 2, then 3

# From [4, 5, 6] → y = 4, then 5, then 6

In [ ]:
# Iterating 3-D Arrays
# In a 3-D array it will go through all the 2-D arrays.

# Example : Iterate on the elements of the following 3-D array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
           print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [ ]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.

# Example : Iterate down to the scalars:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Iterating Arrays Using nditer()
# The function nditer() is a helping function that can be used from very basic to very advanced iterations.
# It solves some basic issues which we face in iteration, lets go through it with examples.

# Iterating on Each Scalar Element
# In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
# Example : Iterate through the following 3-D array:

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr):
   print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Iterating Array With Different Data Types
# We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

# NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

# Example : Iterate through the array as a string:

import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)



np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [ ]:
# Iterating With Different Step Size
# We can use filtering and followed by iteration.

# Example : Iterate through every scalar element of the 2D array skipping 1 element:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)


1
3
5
7


In [ ]:
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one.

# Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

# Example : Enumerate on following 1D arrays elements:

import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)



(0,) 1
(1,) 2
(2,) 3


In [ ]:
# Example : Enumerate on following 2D array's elements:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
 # Exercise : Consider the following code:
import numpy as np
arr = np.array(['a', 'b', 'c'])
for x in arr:
  print('Hello ' + x)


Hello a
Hello b
Hello c


In [ ]:
# Consider the following code:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
# Consider the following code:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
for x in np.nditer(arr[::2]):
  print(x)

1
3
5
7


In [ ]:
# NumPy Joining Array
# Joining NumPy Arrays : oining means putting contents of two or more arrays in a single array.

# In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

# We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

# Example : Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)



[1 2 3 4 5 6]


In [ ]:
# Example : Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)



[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Example : Join two 2-D arrays along rows (axis=0):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# A 2-D array only has two axes:


# axis=0	rows (vertical)

# axis=1	columns (horizontal)

In [ ]:
# Joining Arrays Using Stack Functions

# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

# We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

# We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

# Example :
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Example :
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Stacking Along Rows : NumPy provides a helper function: hstack() to stack along rows.

# Example
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
# Stacking Along Columns : NumPy provides a helper function: vstack()  to stack along columns.

# Example

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)



[[1 2 3]
 [4 5 6]]


In [ ]:
# Stacking Along Height (depth) : NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

# Example
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
# NumPy Splitting Array
# Splitting NumPy Arrays : Splitting is reverse operation of Joining.

# Joining merges multiple arrays into one and Splitting breaks one array into multiple.

# We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

# Example : Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

# Note: The return value is a list containing three arrays.




[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# If the array has less elements than required, it will adjust from the end accordingly.

# Example : Split the array in 4 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)
# Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.





[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
# Split Into Arrays

# The return value of the array_split() method is a list containing each of the split as an array.

# If you split an array into 3 arrays, you can access them from the result just like any array element:

# Example : Access the splitted arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])



[1 2]
[3 4]
[5 6]


In [ ]:
# Splitting 2-D Arrays : Use the same syntax when splitting 2-D arrays.

# Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

# Example : Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

# The example above returns three 2-D arrays.




[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# Example : Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

# The example above returns three 2-D arrays.




[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:

# In addition, you can specify which axis you want to do the split around.

# The example below also returns three 2-D arrays, but they are split along the column (axis=1).

# Example : Split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

# An alternate solution is using hsplit() opposite of hstack()



[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
# Example

# Use the hsplit() method to split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])

[1 2]


In [ ]:
import numpy as np
arr = np.array(['a', 'b', 'c'])
newarr = np.array_split(arr, 3)
print(newarr)

[array(['a'], dtype='<U1'), array(['b'], dtype='<U1'), array(['c'], dtype='<U1')]


In [ ]:
# NumPy Searching Arrays
# Searching Arrays
# You can search an array for a certain value, and return the indexes that get a match.

# To search an array, use the where() method

In [ ]:
# Example : Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

# The example above will return a tuple: (array([3, 5, 6],)

# Which means that the value 4 is present at index 3, 5, and 6.




(array([3, 5, 6]),)


In [ ]:

# Example : Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)




(array([1, 3, 5, 7]),)


In [ ]:
# Example : Find the indexes where the values are odd:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [ ]:
# Search Sorted
#  There is a method called searchsorted() which performs a binary search in the array,
# and returns the index where the specified value would be inserted to maintain the search order.

# The searchsorted() method is assumed to be used on sorted arrays.

In [ ]:
# Example : Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)


1


In [ ]:
# Example explained: The number 7 should be inserted on index 1 to remain the sort order.

# The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

# Search From the Right Side

# By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [ ]:
# Example : Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [ ]:
# Example explained: The number 7 should be inserted on index 2 to remain the sort order.

# The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.

# Multiple Values

# To search for more than one value, use an array with the specified values.



In [ ]:
# Example : Find the indexes where the values 2, 4, and 6 should be inserted:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)
# The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.



[1 2 3]


In [ ]:
import numpy as np
arr = np.array([15, 38, 41, 46])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2]),)


In [ ]:
# NumPy Sorting Arrays
# Sorting Arrays : Sorting means putting elements in an ordered sequence.

# Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

# The NumPy ndarray object has a function called sort(), that will sort a specified array.

# Example : Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

# Note: This method returns a copy of the array, leaving the original array unchanged.




[0 1 2 3]


In [ ]:
# You can also sort arrays of strings, or any other data type:

# Example : Sort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))



['apple' 'banana' 'cherry']


In [ ]:
# Example Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))



[False  True  True]


In [ ]:
# Sorting a 2-D Array
# If you use the sort() method on a 2-D array, both arrays will be sorted:

# Example Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [ ]:
# NumPy Filter Array
# Filtering Arrays
# Getting some elements out of an existing array and creating a new array out of them is called filtering.

# In NumPy, you filter an array using a boolean index list.

# A boolean index list is a list of booleans corresponding to indexes in the array.

# If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.



In [ ]:
# Example : Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)
# The example above will return [41, 43], why?

# Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

[41 43]


In [ ]:
# Creating the Filter Array
# In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

# Example : Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [ ]:
# Example : Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
# Creating Filter Directly From Array : The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

# We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

# Example : Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [ ]:
# Example : Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
import numpy as np
arr = np.array(['a', 'b', 'c'])
x = arr[[True, False, True]]
print(x)

['a' 'c']


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
filter_arr = arr > 3
print(filter_arr)

[False False False  True  True  True]


In [ ]:
import numpy as np
arr = np.array([7, 8, 9, 10])
filter_arr = arr > 9
newarr = arr[filter_arr]
print(newarr)

[10]
